### ISSUE TITLE
The integration stopped to work after upgrade from "Home Assistant Core 2022.6.1" to "Home Assistant Core 2022.6.3".

### ISSUE THREAD

**Issue by gustavstrandberg** [CJNE/thermiagenesis#105]
## Describe the bug

The integration stopped to work after upgrade from "Home Assistant Core 2022.6.1" to "Home Assistant Core 2022.6.3".

## Debug log

```text

Add your logs here.

Logger: custom_components.thermiagenesis
Source: custom_components/thermiagenesis/__init__.py:98
Integration: Thermia Genesis ([documentation](https://github.com/CJNE/thermiagenesis), [issues](https://github.com/CJNE/thermiagenesis/issues))
First occurred: 10:48:03 (4 occurrences)
Last logged: 10:49:07

Unexpected error fetching thermiagenesis data: 'bool' object is not callable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/thermiagenesis/__init__.py", line 98, in _async_update_data
    data = await self.thermia.async_update(only_registers=registers)
  File "/usr/local/lib/python3.9/site-packages/pythermiagenesis/__init__.py", line 65, in async_update
    if not self._client.is_open():
TypeError: 'bool' object is not callable

**Comment by Lord-Bam** [comment]
I have the same issue upgrading from 2022.6.0 to 2022.6.3.
Upgrading to 2022.6.4 did not resolve my issue.

I would add some logs, I but haven't figured out yet where to get them from.

**Comment by gustavstrandberg** [comment]
> I have the same issue upgrading from 2022.6.0 to 2022.6.3. Upgrading to 2022.6.4 did not resolve my issue.
> 
> I would add some logs, I but haven't figured out yet where to get them from.

Hi! 

You can fetch the logs from "Settings - System - Logs" and klick on the "Unexpected error fetching thermiagenesis data: 'bool' object is not callable"

/Gustav

**Comment by Lord-Bam** [comment]
When I reinstall the integration I get a "connection error" message.

my connection from custom.yaml still works:

```
modbus:
  - type: tcp
    name: Thermia
    host: 192.168.0.7
    port: 502
    sensors:
      - name: wp_outside_temp
        unit_of_measurement: °C
        address: 13
        input_type: input
        scan_interval: 300
        data_type: int16
        scale: 0.1
```
