### ISSUE TITLE
Different device_class for alarms

### ISSUE THREAD

**Issue by michaelpiron** [CJNE/thermiagenesis#187]
## Version of the custom_component

0.0.9

## Issue

In [https://github.com/CJNE/thermiagenesis/blob/master/custom_components/thermiagenesis/const.py](https://github.com/CJNE/thermiagenesis/blob/master/custom_components/thermiagenesis/const.py), the different alarms are being defined.

Why do different alarms have different device_class ? Some of the classes are rather confusing to interpret.

Extracts:
Definition of the classes:
```yaml
CLASS_RELAY = "opening"
CLASS_ALARM = "problem"
CLASS_STATE = "plug"
CLASS_ENERGY = "energy"
```

An alarm defined as ALARM/problem:
```yaml
BINARY_SENSOR_TYPES = {
    thermiaconst.ATTR_DINPUT_ALARM_ACTIVE_CLASS_A: {
        ATTR_LABEL: "Alarm Active Class A",
        ATTR_CLASS: CLASS_ALARM,
        ATTR_DEFAULT_ENABLED: False,
    },
```

And an alarm defined as RELAY/opening:
```yaml
    thermiaconst.ATTR_DINPUT_MAXIMUM_TIME_FOR_ANTI_LEGIONELLA_EXCEEDED_ALARM: {
        ATTR_LABEL: "Maximum Time For Anti Legionella Exceeded Alarm",
        ATTR_CLASS: CLASS_RELAY,
        ATTR_DEFAULT_ENABLED: False,
    },
```

The RELAY/opening device_class makes the alarms difficult to interpret in Home Assistant, in my opinion.
For example: This alarm is currently not active, and is represented like this:
![image](https://user-images.githubusercontent.com/4469877/198629121-8f8823de-4d5d-4d7e-9a72-f705b23d37c0.png)
This is confusing, as a closed relay state can be seen as "alarm active".

I had to look in the Developer Tools section of Home Assistant to correctly understand the state. There it says "off":
![image](https://user-images.githubusercontent.com/4469877/198629860-f1d8ff46-10b8-4a15-b79b-82253ca64fae.png)

## Proposal
Proposal to mark all alarm binary sensors as either device_class = None or device_class = Problem.
These seem the most appropriate.
For info, the complete list of device classes for binary sensors:
![image](https://user-images.githubusercontent.com/4469877/198632111-aa20bf45-7b9d-4d17-add1-3a226b75977d.png)
